-- Personenbezogener Lesestatus fuer Mitteilungen. Empfaenger sehen und
-- veraendern ausschliesslich ihre eigenen Lesebestaetigungen.
create table public.message_reads (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages (id) on delete cascade,
  profile_id bigint not null references public.profiles (id) on delete cascade,
  read_at timestamp without time zone not null default now(),
  created_at timestamp without time zone not null default now(),
  constraint message_reads_message_profile_key unique (message_id, profile_id)
);

create index message_reads_profile_id_idx
on public.message_reads (profile_id);

alter table public.message_reads enable row level security;

create policy "Users can read own message receipts"
on public.message_reads
for select
to authenticated
using (profile_id = public.current_profile_id());

create policy "Users can mark accessible messages as read"
on public.message_reads
for insert
to authenticated
with check (
  profile_id = public.current_profile_id()
  and exists (
    select 1
    from public.messages
    where messages.id = message_reads.message_id
  )
);

create policy "Users can refresh own message receipts"
on public.message_reads
for update
to authenticated
using (profile_id = public.current_profile_id())
with check (
  profile_id = public.current_profile_id()
  and exists (
    select 1
    from public.messages
    where messages.id = message_reads.message_id
  )
);

revoke all on table public.message_reads from anon;
grant select, insert, update on table public.message_reads to authenticated;
grant usage, select on sequence public.message_reads_id_seq to authenticated;

comment on table public.message_reads is
  'One private read receipt per profile and accessible message.';
